# TODO: nedokoncene
# ma to byt dockerfile pro kombinaci GO/C++
FROM golang:1-alpine3.12 AS build-image

# install compiler: golang & g++
# pro ucely kompilace C++ interni zateze
RUN apk add --no-cache git g++ make sqlite-dev

# vypinam moduly 
RUN go env -w GOPROXY=direct

# build
WORKDIR /src
ADD . .

# magicka kompilace go handleru pro lambdu
RUN go mod tidy
RUN go build -tags lambda.norpc -ldflags="-s -w" main.go

# kompilace interni binarky
RUN make load

# copy artifacts to a clean image
FROM bash

RUN apk add --no-cache sqlite-dev

COPY --from=build-image /src/main /main
COPY --from=build-image /src/plawsload /plawsload

ENTRYPOINT [ "/main" ] 